Repository CodeLionX/dODo, pull requests merged in 2019-05, with the labels that each got.

#9 Feature/actor setup
  src/main/scala/com/github/codelionx/dodo/Main.scala
  src/main/scala/com/github/codelionx/dodo/actors/DataHolder.scala
  src/main/scala/com/github/codelionx/dodo/actors/ODMaster.scala
  src/main/scala/com/github/codelionx/dodo/actors/Reaper.scala
  src/main/scala/com/github/codelionx/dodo/actors/ResultCollector.scala
  src/main/scala/com/github/codelionx/dodo/actors/SystemCoordinator.scala
Labels: Merge

#6 Implement Data Holder
  src/main/scala/com/github/codelionx/dodo/Main.scala
  src/main/scala/com/github/codelionx/dodo/actors/DataHolder.scala
  src/main/scala/com/github/codelionx/dodo/actors/SystemCoordinator.scala
  src/main/scala/com/github/codelionx/dodo/parsing/CSVParser.scala
  src/main/scala/com/github/codelionx/dodo/types/Implicits.scala
  src/main/scala/com/github/codelionx/dodo/types/TypedColumnBuilder.scala
Labels: Merge

#15 Feature/master logic
  src/main/scala/com/github/codelionx/dodo/actors/DataHolder.scala
  src/main/scala/com/github/codelionx/dodo/actors/ODMaster.scala
  src/main/scala/com/github/codelionx/dodo/actors/SystemCoordinator.scala
  src/main/scala/com/github/codelionx/dodo/actors/Worker.scala
  src/main/scala/com/github/codelionx/dodo/discovery/CandidateGenerator.scala
  src/main/scala/com/github/codelionx/dodo/discovery/Pruning.scala
Labels: Merge

#17 Feature/result collector
  src/main/scala/com/github/codelionx/dodo/Main.scala
  src/main/scala/com/github/codelionx/dodo/actors/ODMaster.scala
  src/main/scala/com/github/codelionx/dodo/actors/ResultCollector.scala
  src/main/scala/com/github/codelionx/dodo/actors/SystemCoordinator.scala
  src/main/scala/com/github/codelionx/dodo/actors/Worker.scala
  src/main/scala/com/github/codelionx/dodo/discovery/CandidateGenerator.scala
Labels: Merge

#19 Use configuration
  src/main/resources/application.conf
  src/main/resources/dodo.conf
  src/main/scala/com/github/codelionx/dodo/Main.scala
  src/main/scala/com/github/codelionx/dodo/Settings.scala
  src/main/scala/com/github/codelionx/dodo/actors/ODMaster.scala
  src/main/scala/com/github/codelionx/dodo/actors/ResultCollector.scala
  src/main/scala/com/github/codelionx/dodo/actors/SystemCoordinator.scala
Labels: Needs Review

#24 Fix tests (were failing due to now working split detection
  src/test/scala/com/github/codelionx/dodo/discovery/DependencyCheckingSpec.scala
Labels: Needs Review

#25 Use config files to specify parsing options
  src/main/resources/dodo.conf
  src/main/resources/reference.conf
  src/main/scala/com/github/codelionx/dodo/Settings.scala
  src/main/scala/com/github/codelionx/dodo/actors/DataHolder.scala
  src/main/scala/com/github/codelionx/dodo/parsing/CSVParser.scala
  src/main/scala/com/github/codelionx/dodo/parsing/TypedColumnProcessor.scala
Labels: Needs Review

#26 Enable CI for PR status
  .travis.yml
  README.md
  project/plugins.sbt
  src/main/scala/com/github/codelionx/dodo/Main.scala
  src/main/scala/com/github/codelionx/dodo/actors/SystemCoordinator.scala
Labels: Blocked, Needs Review

#28 Feature/same results as oc ddiscover
  src/main/resources/dodo.conf
  src/main/resources/reference.conf
  src/main/scala/com/github/codelionx/dodo/Settings.scala
  src/main/scala/com/github/codelionx/dodo/actors/Worker.scala
Labels: Merge

#34 fix logic error
  src/main/scala/com/github/codelionx/dodo/actors/Worker.scala
Labels: Merge

#38 Data Serialization
  build.sbt
  src/main/resources/application.conf
  src/main/scala/com/github/codelionx/dodo/types/DataType.scala
  src/main/scala/com/github/codelionx/dodo/types/DateFormat.scala
  src/main/scala/com/github/codelionx/dodo/types/TypedColumn.scala
  src/main/scala/com/github/codelionx/dodo/types/TypedColumnBase.scala
  src/test/scala/com/github/codelionx/dodo/ODDetectionSpec.scala
  src/test/scala/com/github/codelionx/dodo/SerializationSpec.scala
  src/test/scala/com/github/codelionx/dodo/parsing/TypeInferrerSpec.scala
  src/test/scala/com/github/codelionx/dodo/types/DataTypeSpec.scala
Labels: Merge
